### PR TITLE
Updated default port to 3000 for CORS

### PR DESCRIPTION
**Pull request by jlyshoel**
As I think react is running on port 3000 as default, it makes sense to set the default to 3000 as well here I think. We've run into a couple of issues already which I think are related to this setting.

### CODE REVIEW

**Review by pettermk — COMMENTED** [review]
If you are making changes here anyway, maybe it should just be empty so if you forget to set something you don't expose the app to requests from localhost unnecessarily? E.g. our frontends don't need CORS settings and maybe it should not be required to pass an empty array to tell you don't need to allow any other origins. I made this default value in the first place to make less hassle for template users when I split out the application insights.

**Comment by jlyshoel** [comment]
Maybe that's better, then we just have to set CORS in each app

**Review by lp-code — APPROVED** [review]

**Comment by jlyshoel** [comment]
I've updated to an empty list now, with a trick for getting passed the ARM TTK

**Review by pettermk — APPROVED** [review]
LGTM

**Pull request merged**
