### PR TITLE
Output resourceId of created data factory

### PR DESCRIPTION
**Pull request by niktho**
To ease the creation of Data Factory alerts on the outside of this template expose the resourceId of the created data factory.

### CODE REVIEW

**Comment by lp-code** [comment]
Failing tests?

**Comment by niktho** [comment]
Yes, it’s the resourceApp module that is failing. Asked Jo to look into the API version for that ARM template.

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Lars Pesch <notifications@github.com>
Sendt: Wednesday, September 9, 2020 6:12:45 PM
Til: equinor/ioc-shared-infrastructure <ioc-shared-infrastructure@noreply.github.com>
Kopi: Nikolai Thomassen <nikolai.k.thomassen@avanade.com>; Author <author@noreply.github.com>
Emne: Re: [equinor/ioc-shared-infrastructure] Output resourceId of created data factory (#25)


This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.

________________________________

Failing tests?

**Comment by jlyshoel** [comment]
Added an upgrade PR for the API version. Seems they've launched a new version of the API and/or the TTK. 
https://github.com/equinor/ioc-shared-infrastructure/pull/27

**Comment by niktho** [comment]
@lp-code @jlyshoel , I have updated this branch based on master containing the latest corrections. Do you have time to validate this PR?

**Review by jlyshoel — APPROVED** [review]

**Pull request merged**
